apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - poddisruptionbudget.yaml
images:
  - name: kenkomirai/backend
    newTag: 1.2.0
  - name: kenkomirai/frontend
    newTag: 1.2.0
