apiVersion: v1
kind: Service
metadata:
  name: covid-simulation-service
spec:
  selector:
    app: covid-simulation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
