apiVersion: v1
kind: Service
metadata:
  name: kenkomirai-backend
  namespace: kenkomirai
  labels:
    app.kubernetes.io/name: kenkomirai-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kenkomirai-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: kenkomirai-frontend
  namespace: kenkomirai
  labels:
    app.kubernetes.io/name: kenkomirai-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kenkomirai-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
